// <auto-generated />
using MaoriSouvenirShopping.Data;
using MaoriSouvenirShopping.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MaoriSouvenirShopping.Migrations
{
    [DbContext(typeof(WebShopContext))]
    partial class WebShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaoriSouvenirShopping.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoryName");

                    b.Property<string>("Description");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("MaoriSouvenirShopping.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("CustomerID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("MaoriSouvenirShopping.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerID");

                    b.Property<DateTime>("OrderDate");

                    b.Property<int>("Status");

                    b.Property<double>("TotalCost");

                    b.HasKey("OrderID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("MaoriSouvenirShopping.Models.OrderItem", b =>
                {
                    b.Property<int>("SouvenirID");

                    b.Property<int>("OrderID");

                    b.Property<int>("ItemAmount");

                    b.HasKey("SouvenirID", "OrderID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("MaoriSouvenirShopping.Models.Souvenir", b =>
                {
                    b.Property<int>("SouvenirID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryID");

                    b.Property<string>("Description");

                    b.Property<string>("PhotoPath");

                    b.Property<double>("Price");

                    b.Property<string>("SouvenirName");

                    b.Property<int>("SupplierID");

                    b.HasKey("SouvenirID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("SupplierID");

                    b.ToTable("Souvenir");
                });

            modelBuilder.Entity("MaoriSouvenirShopping.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("SupplierID");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("MaoriSouvenirShopping.Models.Order", b =>
                {
                    b.HasOne("MaoriSouvenirShopping.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MaoriSouvenirShopping.Models.OrderItem", b =>
                {
                    b.HasOne("MaoriSouvenirShopping.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MaoriSouvenirShopping.Models.Souvenir", "Souvenir")
                        .WithMany("OrderItems")
                        .HasForeignKey("SouvenirID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MaoriSouvenirShopping.Models.Souvenir", b =>
                {
                    b.HasOne("MaoriSouvenirShopping.Models.Category", "Category")
                        .WithMany("Souvenirs")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MaoriSouvenirShopping.Models.Supplier", "Supplier")
                        .WithMany("Souvenirs")
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
